const baseDados = [
  {
    "ID": 1,
    "Data": "2026-01-06",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 5,
    "Presenças": 5,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 51.7,
    "Depois": 53.5,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.03481624758220497,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 2,
    "Data": "2026-01-07",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 5,
    "Presenças": 5,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.6,
    "Indicador": "Qualidade",
    "Antes": 93.9,
    "Depois": 91.7,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": -0.023429179978700775,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 3,
    "Data": "2026-01-08",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 51,
    "Presenças": 51,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.3,
    "Indicador": "Qualidade",
    "Antes": 66.8,
    "Depois": 70.3,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.05239520958083833,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 4,
    "Data": "2026-01-09",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.6,
    "Indicador": "Qualidade",
    "Antes": 63.5,
    "Depois": 69.2,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.0897637795275591,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 5,
    "Data": "2026-01-10",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "INGRID MARQUES",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 15,
    "Presenças": 15,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.8,
    "Indicador": "Qualidade",
    "Antes": 55.3,
    "Depois": 57.1,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.032549728752260476,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 6,
    "Data": "2026-01-12",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Jeanne",
    "Supervisor": "Carina Reis",
    "Turma": 6,
    "Participantes": 6,
    "Presenças": 6,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.7,
    "Indicador": "Qualidade",
    "Antes": 53.1,
    "Depois": 52.3,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": -0.015065913370998196,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 7,
    "Data": "2026-01-13",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 7,
    "Participantes": 7,
    "Presenças": 7,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.5,
    "Indicador": "Qualidade",
    "Antes": 51,
    "Depois": 53,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.0392156862745098,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 8,
    "Data": "2026-01-14",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 8,
    "Participantes": 11,
    "Presenças": 11,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.1,
    "Indicador": "Qualidade",
    "Antes": 53.6,
    "Depois": 55.6,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.03731343283582089,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 9,
    "Data": "2026-01-16",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 9,
    "Participantes": 13,
    "Presenças": 13,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.7,
    "Indicador": "Qualidade",
    "Antes": 53.7,
    "Depois": 53.3,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": -0.007448789571694705,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 10,
    "Data": "2026-01-19",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Eliene",
    "Supervisor": "Carina Reis",
    "Turma": 10,
    "Participantes": 8,
    "Presenças": 8,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.4,
    "Indicador": "Qualidade",
    "Antes": 77.4,
    "Depois": 78.8,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.01808785529715751,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 11,
    "Data": "2026-01-20",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "INGRID MARQUES",
    "Supervisor": "Carina Reis",
    "Turma": 11,
    "Participantes": 7,
    "Presenças": 7,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.3,
    "Indicador": "Qualidade",
    "Antes": 52.8,
    "Depois": 51.7,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": -0.020833333333333228,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 12,
    "Data": "2026-01-21",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 12,
    "Participantes": 6,
    "Presenças": 6,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.4,
    "Indicador": "Qualidade",
    "Antes": 92.7,
    "Depois": 98.5,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.06256742179072274,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 13,
    "Data": "2026-01-22",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Eliene",
    "Supervisor": "Carina Reis",
    "Turma": 13,
    "Participantes": 30,
    "Presenças": 30,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.3,
    "Indicador": "Qualidade",
    "Antes": 94.7,
    "Depois": 98.5,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.04012671594508973,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 14,
    "Data": "2026-01-23",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 14,
    "Participantes": 25,
    "Presenças": 25,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.4,
    "Indicador": "Qualidade",
    "Antes": 92.8,
    "Depois": 97.4,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.04956896551724147,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 15,
    "Data": "2026-01-24",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 15,
    "Participantes": 2,
    "Presenças": 2,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8,
    "Indicador": "Qualidade",
    "Antes": 66,
    "Depois": 66.2,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.0030303030303030732,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 16,
    "Data": "2026-01-26",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "JAILSON",
    "Supervisor": "Carina Reis",
    "Turma": 16,
    "Participantes": 5,
    "Presenças": 5,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.6,
    "Indicador": "Qualidade",
    "Antes": 66,
    "Depois": 64.3,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": -0.025757575757575802,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 17,
    "Data": "2026-01-27",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 17,
    "Participantes": 4,
    "Presenças": 4,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.7,
    "Indicador": "Qualidade",
    "Antes": 53.6,
    "Depois": 52.8,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": -0.014925373134328438,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 18,
    "Data": "2026-01-29",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 18,
    "Participantes": 5,
    "Presenças": 5,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.3,
    "Indicador": "Qualidade",
    "Antes": 90.9,
    "Depois": 98.8,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.08690869086908681,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 19,
    "Data": "2026-02-02",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "JAILSON",
    "Supervisor": "Carina Reis",
    "Turma": 19,
    "Participantes": 4,
    "Presenças": 4,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.1,
    "Indicador": "Qualidade",
    "Antes": 82.6,
    "Depois": 82.2,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": -0.0048426150121064345,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 20,
    "Data": "2026-02-03",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Jeanne",
    "Supervisor": "Carina Reis",
    "Turma": 20,
    "Participantes": 3,
    "Presenças": 3,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.5,
    "Indicador": "Qualidade",
    "Antes": 50.6,
    "Depois": 56.5,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.11660079051383396,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 21,
    "Data": "2026-02-05",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "JAILSON",
    "Supervisor": "Carina Reis",
    "Turma": 21,
    "Participantes": 4,
    "Presenças": 4,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.6,
    "Indicador": "Qualidade",
    "Antes": 84.4,
    "Depois": 86,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.018957345971563913,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 22,
    "Data": "2026-02-07",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Cadastro e tabulação",
    "Instrutor": "Jeanne",
    "Supervisor": "Carina Reis",
    "Turma": 22,
    "Participantes": 2,
    "Presenças": 2,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.5,
    "Indicador": "Qualidade",
    "Antes": 89.3,
    "Depois": 97,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.08622620380739085,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 23,
    "Data": "2026-01-12",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 10,
    "Presenças": 10,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.9,
    "Indicador": "Qualidade",
    "Antes": 85.3,
    "Depois": 84.1,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": -0.014067995310668263,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 24,
    "Data": "2026-01-13",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "JEANNE",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 2,
    "Presenças": 2,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.6,
    "Indicador": "Qualidade",
    "Antes": 69.9,
    "Depois": 74.2,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.06151645207439194,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 25,
    "Data": "2026-01-17",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "ELIENE",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 28,
    "Presenças": 28,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9,
    "Indicador": "Qualidade",
    "Antes": 91.5,
    "Depois": 101,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.10382513661202186,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 26,
    "Data": "2026-01-19",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "JAILSON",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 16,
    "Presenças": 16,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 69.3,
    "Depois": 69.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.0014430014430015662,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 27,
    "Data": "2026-01-20",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "JAILSON",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 10,
    "Presenças": 10,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.6,
    "Indicador": "Qualidade",
    "Antes": 67.9,
    "Depois": 70.8,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.04270986745213536,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 28,
    "Data": "2026-01-21",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "ELIENE",
    "Supervisor": "Carina Reis",
    "Turma": 6,
    "Participantes": 22,
    "Presenças": 22,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8,
    "Indicador": "Qualidade",
    "Antes": 82.5,
    "Depois": 80.3,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": -0.0266666666666667,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 29,
    "Data": "2026-01-22",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "Eliene Alves",
    "Supervisor": "Carina Reis",
    "Turma": 7,
    "Participantes": 14,
    "Presenças": 14,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.3,
    "Indicador": "Qualidade",
    "Antes": 93.7,
    "Depois": 92.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": -0.013874066168623234,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 30,
    "Data": "2026-01-23",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "Eliene Alves",
    "Supervisor": "Carina Reis",
    "Turma": 8,
    "Participantes": 20,
    "Presenças": 20,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.4,
    "Indicador": "Qualidade",
    "Antes": 81.5,
    "Depois": 80.1,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": -0.01717791411042952,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 31,
    "Data": "2026-01-24",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "Júlia Taís",
    "Supervisor": "Carina Reis",
    "Turma": 9,
    "Participantes": 3,
    "Presenças": 3,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 77.4,
    "Depois": 77.7,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.003875968992248025,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 32,
    "Data": "2026-01-29",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "MELISE",
    "Supervisor": "Carina Reis",
    "Turma": 10,
    "Participantes": 5,
    "Presenças": 5,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.4,
    "Indicador": "Qualidade",
    "Antes": 92.2,
    "Depois": 102.8,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.11496746203904548,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 33,
    "Data": "2026-01-30",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "MELISE",
    "Supervisor": "Carina Reis",
    "Turma": 11,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.4,
    "Indicador": "Qualidade",
    "Antes": 62.2,
    "Depois": 67.8,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.09003215434083592,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 34,
    "Data": "2026-02-02",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "JAILSON",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 4,
    "Presenças": 4,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.3,
    "Indicador": "Qualidade",
    "Antes": 79.5,
    "Depois": 83.6,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.05157232704402508,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 35,
    "Data": "2026-02-03",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 4,
    "Presenças": 4,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.8,
    "Indicador": "Qualidade",
    "Antes": 87.7,
    "Depois": 85.3,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": -0.027366020524515457,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 36,
    "Data": "2026-02-05",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 5,
    "Presenças": 5,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.9,
    "Indicador": "Qualidade",
    "Antes": 76.9,
    "Depois": 82.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.07412223667100115,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 37,
    "Data": "2026-02-06",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "Júlia Taís",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 4,
    "Presenças": 4,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.7,
    "Indicador": "Qualidade",
    "Antes": 61,
    "Depois": 68,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.11475409836065574,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 38,
    "Data": "2026-02-09",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Raça e cor nos registros SEBRAE",
    "Instrutor": "Júlia Taís",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 1,
    "Presenças": 1,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.8,
    "Indicador": "Qualidade",
    "Antes": 61.2,
    "Depois": 66.5,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.08660130718954244,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 39,
    "Data": "2026-01-18",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "LORNI",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 19,
    "Presenças": 19,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.9,
    "Indicador": "Qualidade",
    "Antes": 53.8,
    "Depois": 59.9,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.11338289962825282,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 40,
    "Data": "2026-01-24",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "LORNI",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.8,
    "Indicador": "Qualidade",
    "Antes": 87.1,
    "Depois": 93.8,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.07692307692307696,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 41,
    "Data": "2026-01-25",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "LORNI",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 10,
    "Presenças": 10,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.1,
    "Indicador": "Qualidade",
    "Antes": 93.2,
    "Depois": 95.7,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.02682403433476395,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 42,
    "Data": "2026-01-26",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "MELISE",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 7,
    "Presenças": 7,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.3,
    "Indicador": "Qualidade",
    "Antes": 83.7,
    "Depois": 87.5,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.04540023894862601,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 43,
    "Data": "2026-01-27",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "JEANNE",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 14,
    "Presenças": 14,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9,
    "Indicador": "Qualidade",
    "Antes": 60.4,
    "Depois": 64.5,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.06788079470198678,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 44,
    "Data": "2026-02-01",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "ELIENE",
    "Supervisor": "Carina Reis",
    "Turma": 6,
    "Participantes": 18,
    "Presenças": 18,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.7,
    "Indicador": "Qualidade",
    "Antes": 61.4,
    "Depois": 66.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.08143322475570045,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 45,
    "Data": "2026-02-26",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Agendamento e Consultoria",
    "Instrutor": "JULIA TAÍS",
    "Supervisor": "Carina Reis",
    "Turma": 7,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.7,
    "Indicador": "Qualidade",
    "Antes": 81.1,
    "Depois": 86.9,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.07151664611590644,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 46,
    "Data": "2026-02-02",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Formação em libras ",
    "Instrutor": "ELIENE",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 1,
    "Presenças": 1,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.6,
    "Indicador": "Qualidade",
    "Antes": 92.1,
    "Depois": 89.6,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": -0.02714440825190011,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 47,
    "Data": "2026-02-05",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Migração ouvidoria ",
    "Instrutor": "JULIA TAÍS",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 2,
    "Presenças": 2,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.6,
    "Indicador": "Unificação",
    "Antes": 83.6,
    "Depois": 84.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.009569377990430759,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 47,
    "Data": "2026-01-09",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Reciclagem( Geral, Dasn, retorno de férias, retorno INSS)",
    "Instrutor": "MELISE",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.6,
    "Indicador": "Qualidade",
    "Antes": 83.6,
    "Depois": 84.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.009569377990430759,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 47,
    "Data": "2026-02-06",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Reciclagem( Geral, Dasn, retorno de férias, retorno INSS)",
    "Instrutor": "MELISE",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 1,
    "Presenças": 1,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.6,
    "Indicador": "Qualidade",
    "Antes": 83.6,
    "Depois": 84.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.009569377990430759,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 48,
    "Data": "2026-03-18",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Reciclagem( Geral, Dasn, retorno de férias, retorno INSS)",
    "Instrutor": "MELISE",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 7,
    "Presenças": 7,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.1,
    "Indicador": "Qualidade",
    "Antes": 50.2,
    "Depois": 52.4,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.043824701195219036,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 49,
    "Data": "2026-01-22",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Laboratorio de processos de agendamento ",
    "Instrutor": "JEANNE",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 28,
    "Presenças": 28,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.4,
    "Indicador": "Qualidade",
    "Antes": 64.6,
    "Depois": 65.9,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.020123839009288103,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 50,
    "Data": "2026-02-06",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Laboratorio de processos de agendamento ",
    "Instrutor": "JEANNE",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 6,
    "Presenças": 7,
    "Faltas": -1,
    "% Presença": 1.1666666666666667,
    "Avaliação (0-10)": 8.1,
    "Indicador": "Qualidade",
    "Antes": 66.2,
    "Depois": 68.5,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.03474320241691838,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 51,
    "Data": "2026-02-05",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Laboratorio de processos de agendamento ",
    "Instrutor": "JEANNE",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 7,
    "Presenças": 6,
    "Faltas": 1,
    "% Presença": 0.8571428571428571,
    "Avaliação (0-10)": 9.7,
    "Indicador": "Qualidade",
    "Antes": 73,
    "Depois": 72.9,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": -0.0013698630136985523,
    "Impacto_Pos (0/1)": 0
  },
  {
    "ID": 52,
    "Data": "2026-01-08",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Sala do empreendedor ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 10,
    "Presenças": 10,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.3,
    "Indicador": "Qualidade",
    "Antes": 79,
    "Depois": 80,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.012658227848101266,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 53,
    "Data": "2026-01-26",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Sala do empreendedor ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.7,
    "Indicador": "Qualidade",
    "Antes": 68.3,
    "Depois": 68.7,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.0058565153733529385,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 54,
    "Data": "2026-01-31",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Sala do empreendedor ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 13,
    "Presenças": 13,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.4,
    "Indicador": "Qualidade",
    "Antes": 74.8,
    "Depois": 77.6,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.037433155080213866,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 55,
    "Data": "2026-02-18",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Sala do empreendedor ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 10,
    "Presenças": 10,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8,
    "Indicador": "Qualidade",
    "Antes": 64.4,
    "Depois": 66,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.024844720496894318,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 56,
    "Data": "2026-01-27",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "INGRID MARQUES",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 15,
    "Presenças": 15,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.9,
    "Indicador": "unificação",
    "Antes": 72.4,
    "Depois": 76.5,
    "Janela (dias)": 15,
    "Observações": "",
    "Evolução %": 0.056629834254143564,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 57,
    "Data": "2026-02-13",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "JEANNE",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 18,
    "Presenças": 18,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 8.8,
    "Indicador": "unificação",
    "Antes": 92.9,
    "Depois": 101.9,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.0968783638320775,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 58,
    "Data": "2026-02-23",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 1,
    "Presenças": 1,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.6,
    "Indicador": "unificação",
    "Antes": 93.8,
    "Depois": 94.5,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.007462686567164209,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-02-26",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 19,
    "Presenças": 19,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "unificação",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-03-03",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 6,
    "Presenças": 6,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "unificação",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-03-10",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 6,
    "Participantes": 7,
    "Presenças": 7,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "unificação",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-03-11",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 7,
    "Participantes": 9,
    "Presenças": 9,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "unificação",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-03-24",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Piloto Multiskil ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 8,
    "Participantes": 13,
    "Presenças": 13,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "unificação",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-01-23",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Tira- dúvidas MARKETUP",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 13,
    "Presenças": 13,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-01-30",
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Tira- dúvidas MARKETUP",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 8,
    "Presenças": 8,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-02-06",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Tira- dúvidas MARKETUP",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 6,
    "Presenças": 6,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-02-13",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Tira- dúvidas MARKETUP",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 13,
    "Presenças": 13,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-02-21",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Tira- dúvidas MARKETUP",
    "Instrutor": "Melise",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 16,
    "Presenças": 16,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 59,
    "Data": "2026-02-09",
    "Semana_ISO": "#NAME?",
    "Mês": 2,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Treinamento SP",
    "Instrutor": "JULIA TAÍS",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 10,
    "Presenças": 10,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 9.2,
    "Indicador": "Qualidade",
    "Antes": 85.2,
    "Depois": 85.6,
    "Janela (dias)": 7,
    "Observações": "",
    "Evolução %": 0.004694835680751073,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": "2026-03-03",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Abertura de feedback ( ação de piso) ",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 295,
    "Presenças": 295,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "NPS",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": "2026-03-20",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "DASN LORNI",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 14,
    "Presenças": 14,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": "2026-03-21",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "DASN LORNI",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 2,
    "Participantes": 19,
    "Presenças": 19,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": "2026-03-23",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "DASN LORNI",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 3,
    "Participantes": 56,
    "Presenças": 56,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": "2026-03-24",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "DASN LORNI",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 4,
    "Participantes": 20,
    "Presenças": 20,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": "2026-03-25",
    "Semana_ISO": "#NAME?",
    "Mês": 3,
    "Ano": 2026,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "DASN LORNI",
    "Instrutor": "FABIANA",
    "Supervisor": "Carina Reis",
    "Turma": 5,
    "Participantes": 15,
    "Presenças": 15,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "Qualidade",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": null,
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 1900,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Qualidade",
    "Instrutor": "Bruno",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 11,
    "Presenças": 11,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": null,
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": null,
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 1900,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Qualidade",
    "Instrutor": "Bruno",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 11,
    "Presenças": 11,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "TMA",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": null,
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 1900,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Qualidade",
    "Instrutor": "Bruno",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 11,
    "Presenças": 11,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "TMA",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  },
  {
    "ID": 60,
    "Data": null,
    "Semana_ISO": "#NAME?",
    "Mês": 1,
    "Ano": 1900,
    "Cliente": "SEBRAE",
    "Tipo_Treinamento": "Qualidade",
    "Instrutor": "Bruno",
    "Supervisor": "Carina Reis",
    "Turma": 1,
    "Participantes": 11,
    "Presenças": 11,
    "Faltas": 0,
    "% Presença": 1,
    "Avaliação (0-10)": 7.2,
    "Indicador": "TMA",
    "Antes": 67.5,
    "Depois": 67.7,
    "Janela (dias)": 30,
    "Observações": "",
    "Evolução %": 0.002962962962963005,
    "Impacto_Pos (0/1)": 1
  }
];

export default baseDados;
