CREATE TABLE rps (
  id                   INT PRIMARY KEY AUTO_INCREMENT,
  empresa_id           INT NOT NULL,
  mes_referencia       DATE NOT NULL,
  site                 VARCHAR(100) NOT NULL,
  setor                ENUM('OPERACIONAL','ESTRATÉGICO') NOT NULL,
  chamado              VARCHAR(200) NULL,
  produto              VARCHAR(150) NOT NULL,
  cargo                VARCHAR(200) NULL,
  data_recebimento     DATE NULL,
  status               ENUM('EM ANDAMENTO','ENTREGUE','NÃO ENTREGUE','CANCELADA') NOT NULL DEFAULT 'EM ANDAMENTO',
  inicio_av_tecnica    DATE NULL,
  final_av_tecnica     DATE NULL,
  data_fechamento_vaga DATE NULL,
  hcs                  INT NOT NULL DEFAULT 0,
  hcs_com_to           INT NOT NULL DEFAULT 0,
  hcs_aprovados        INT NOT NULL DEFAULT 0,
  qtd_entregue         INT NOT NULL DEFAULT 0,
  observacoes          TEXT NULL,
  created_by           INT NULL,
  updated_by           INT NULL,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rps_empresa (empresa_id),
  INDEX idx_rps_mes     (mes_referencia),
  INDEX idx_rps_site    (site),
  INDEX idx_rps_setor   (setor),
  INDEX idx_rps_status  (status)
);
